# Setup environment for Docker
language: generic
services: docker
dist: trusty
notifications:
  email: false

# Environment setup before test script. Runs for each build
before_install:
  # Construct the correct container image tag corresponding to this branch/pull
  - CONTIKER_TAG=`git log -1 --oneline -- tools/docker/ | cut -d" " -f1`
  - DOCKER_IMG=$DOCKER_BASE_IMG:$CONTIKER_TAG
  # Try to download the image from dockerhub. If it works, use it.
  #
  # If however it fails then we are most likely looking at a branch or pull
  # that touched tools/docker. In this case, build the image.
  #
  # Any build error will count as Travis test failure.
  #
  # If the test was triggered by a branch update (e.g. a PR merge) then push
  # the new image to dockerhub. This will only happen for builds against
  # contiki-ng/contiki-ng, not for builds on forks.
  - echo "Will use $DOCKER_IMG for this run"
  - >
    echo "Pulling image $DOCKER_IMG from dockerhub";
    docker pull $DOCKER_IMG;
    if [ $? != 0 ]; then
      echo $CONTIKER_TAG "does not exist or pull failed";
      echo "This is normal for PR builds and for builds on forks";
      echo "Building from dockerfile";
      docker build tools/docker -t $DOCKER_IMG;
      if [ $? != 0 ]; then
        echo "Failed to build Docker image"
        exit 1
      fi
      if [ $TRAVIS_REPO_SLUG == contiki-ng/contiki-ng ] && [ $TRAVIS_PULL_REQUEST == false ]; then
        echo "This is a branch build that updates the container. Push image to Dockerhub"
        echo $DOCKERHUB_PASSWD | docker login --username contiker --password-stdin
        docker push $DOCKER_IMG;
        if [ $TRAVIS_BRANCH == develop ] || [ $TRAVIS_BRANCH == master ]; then
          echo "This is a merge in branch $TRAVIS_BRANCH";
          echo "Push also $DOCKER_BASE_IMG:$TRAVIS_BRANCH";
          docker tag $DOCKER_IMG $DOCKER_BASE_IMG:$TRAVIS_BRANCH;
          docker push $DOCKER_BASE_IMG:$TRAVIS_BRANCH;
        fi
      fi
    fi

  # Build Cooja conditionally
  - if [ ${BUILD_COOJA:-false} = true ] ; then
      ant -q -f $CNG_HOST_PATH/tools/cooja/build.xml jar ;
    fi

  # Create a directory for out of tree tests and clone the test repo therein
  # The directory will need created unconditionally so we can always chgrp and
  # mount it, even if empty. Checkout a pre-defined version.
  - mkdir -p $OUT_OF_TREE_TEST_PATH
  - if [ ${TEST_NAME} = "out-of-tree-build" ] ; then
      git clone --depth 1 https://github.com/contiki-ng/out-of-tree-tests $OUT_OF_TREE_TEST_PATH &&
      cd $OUT_OF_TREE_TEST_PATH &&
      git checkout $OUT_OF_TREE_TEST_VER ;
    fi
  # Set permissions for Docker mount
  - sudo chgrp -hR 1000 $CNG_HOST_PATH $OUT_OF_TREE_TEST_PATH

# The test script for each build
script:
  - docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v $OUT_OF_TREE_TEST_PATH:/home/user/out-of-tree-tests -v $CNG_HOST_PATH:/home/user/contiki-ng -ti $DOCKER_IMG bash --login -c "make -C tests/??-$TEST_NAME";
  # Check outcome of the test
  - $CNG_HOST_PATH/tests/check-test.sh $CNG_HOST_PATH/tests/??-$TEST_NAME; exit $?;

# Environment variables
env:
  # Global environment variables, i.e., set for all builds
  global:
    - DOCKER_BASE_IMG='contiker/contiki-ng'
    - CNG_HOST_PATH=`pwd`
    - OUT_OF_TREE_TEST_PATH=$HOME/out-of-tree-tests
    - OUT_OF_TREE_TEST_VER=2869ae7
    # Encrypted environment variables.
    # Only available on builds of contiki-ng/contiki-ng branches, not PRs or forks.
    - secure: 0nrV5yjpT2kE19Hlm7t619Qbmyjx/G7bSUI1c+U3kZbyuxnRlASjVcDN5uPBoimIfGiBRI0nRq690BogAJt4EKwbC1Dy8kC1XD8mRtQ2AIZ6PHaUoG9iS5sBhFBQK0XkB83bwh6omRn/04O0uuX74ooSWT7fDrWxi/y5+0ysXK6gRtOhdrJ3FU5OkNVewX8NeCdx3pOWhMOtXWdFkMIi1XRdDnvMM5/hHlHMkdXXtaZQX9UsK3Q3DSjPRLZjKRiOlcx9MIg2ebh9ITmd2Du2p2q/LKtoutJckvhbKQPWcZi/B+1ZTSff0FHBIg+EYxf6TeFuia7XSTWH7sr2CDCCtcvSR9bB5yW6jdmGfa8Af8I1TCBuqoSUo0Re50BZBZF7COleEh+IojbjXn2CIDMg5rT4Sh3qcMGvFn9OW1cz5h5UNSOk7EIAXXPcI7Aloxh2sBo4/DrvvbfIsKrvxV9Fx4bdyNtR7dZ7xsoOw6L0zttC3K9naf3VAOeBAyjBiRwm0tWxJC/buhTsKlYrthhyUrwLtYAFL4UHcazvz57hY/cEzR2X6F//9Hp7HFoNtn1E36doX3ZfeI22yxHMo9SYW7O69C45wbhJ29lAA9XXbYVyGBKFkY8C1NCZ0Xckt9H8/Ow5Sz8HmW/NNBJCn0Fsx+jezdGc4ED5naugNbLAyNg=
  # Each line in the 'matrix' triggers a separate Travis build
  matrix:
    - TEST_NAME='compile-base'
    - TEST_NAME='compile-arm-ports-01'
    - TEST_NAME='compile-arm-ports-02'
    - TEST_NAME='rpl-lite' BUILD_COOJA=true
    - TEST_NAME='rpl-classic' BUILD_COOJA=true
    - TEST_NAME='6tisch-msf' BUILD_COOJA=true
    - TEST_NAME='tun-rpl-br' BUILD_COOJA=true
    - TEST_NAME='coap-lwm2m'
    - TEST_NAME='script-base'
    - TEST_NAME='simulation-base' BUILD_COOJA=true
    - TEST_NAME='ieee802154' BUILD_COOJA=true
    - TEST_NAME='compile-nxp-ports'
    - TEST_NAME='documentation'
    - TEST_NAME='compile-tools'
    - TEST_NAME='native-runs'
    - TEST_NAME='ipv6' BUILD_COOJA=true
    - TEST_NAME='ipv6-nbr' BUILD_COOJA=true
    - TEST_NAME='out-of-tree-build'
    - TEST_NAME='packet-parsing'
