CFLAGS += -DBUILD_WITH_MSF=1

ifeq ("${TARGET}","cooja")
ifeq ("$(COOJA_NOARCH)","0")
# without COOJA_NOARCH cooja library can`t eliminate unused symbols properly
# so need to ensure that shell willbe in mote library  
MODULES += os/services/shell
#endif
endif

# link msf-shell, if shell service used 
ifeq ("$(filter os/services/shell, $(MODULES))","os/services/shell")
MODULES += os/services/msf/shell
endif
