CONTIKI_PROJECT = 6lr
all: $(CONTIKI_PROJECT)
CONTIKI = ../../..

MAKE_MAC = MAKE_MAC_TSCH
MODULES += os/net/mac/tsch/sixtop
MODULES += os/services/msf
MODULES += os/services/shell

include $(CONTIKI)/Makefile.include
